import type { StrategyPack } from "./types";

/**
 * One-click playbooks compiled from common retail/YouTube systems
 * (ORB+VWAP, EMA pullback, ICT/SMC, Z-Score, ADX/DI, Aroon, Jurik).
 * Educational packaging — not financial advice / not official affiliations.
 */
export const STRATEGY_PACKS: StrategyPack[] = [
  {
    id: "orb_vwap_momentum",
    name: "ORB + VWAP Momentum",
    shortName: "ORB·VWAP",
    category: "momentum",
    inspiredBy: "Ross Cameron / Warrior-style ORB + VWAP (YouTube day-trading)",
    summary:
      "Açılış aralığı kırılımı + VWAP üstü momentum. 9/20 EMA ‘bone zone’, hacim teyidi.",
    howTo: [
      "TF 5m (veya 1m). İlk 5–15 dk high/low’u işaretle (manuel / formasyon).",
      "Long: fiyat OR high üstü + VWAP üstü + 9 EMA tutuyor.",
      "Stop: VWAP altı veya range low. Hedef: 1–2R, kalanı 9 EMA trail.",
      "Tarayıcı: Crypto gainers / hacim spike ile aday üret.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "ema", params: { period: 20 }, color: "#ff9800" },
      { type: "atr", params: { period: 14 } },
      { type: "volumeOsc", params: { shortPeriod: 5, longPeriod: 10 } },
    ],
    risk: {
      rMultiple: 2,
      tip: "İlk 1–2 saatte kal; 3 arka arkaya stop → günü kapat.",
    },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: {
      fast: 9,
      slow: 20,
      useAtrStops: true,
      slAtrMult: 1.2,
      tpAtrMult: 2,
      allowShort: true,
    },
    scannerPresets: ["crypto_gainers", "hacim_ema", "momentum_breakout"],
    scannerChips: ["vol2", "ema_b"],
    tags: ["ORB", "VWAP", "daytrade", "YouTube"],
  },
  {
    id: "ema_pullback_trend",
    name: "EMA 9/21 Pullback",
    shortName: "EMA PB",
    category: "trend",
    inspiredBy: "Classic YouTube trend-pullback (9/21 EMA ride)",
    summary:
      "Trend yönünde 9/21 EMA pullback. Fiyat EMA’ya iner, tutar, devam.",
    howTo: [
      "TF 15m veya 1h. 9 EMA > 21 EMA = long bias.",
      "Pullback 9 veya 21’e; rejection mum + hacim.",
      "Stop: son swing altı / 21 EMA altı. TP: 1.5–2.5R.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "sma", params: { period: 200 }, color: "#78909c" },
      { type: "rsi", params: { period: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "200 SMA karşıtı pullback’lere dikkat." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 9, slow: 21, useAtrStops: true, allowShort: true },
    scannerPresets: ["multi_long", "macd_bull"],
    scannerChips: ["ema_b", "sma50a"],
    tags: ["EMA", "pullback", "trend"],
  },
  {
    id: "ict_smc_kit",
    name: "ICT / SMC Kit",
    shortName: "SMC",
    category: "smc_ict",
    inspiredBy: "ICT killzones + community SMC (OB, FVG, BOS, liquidity)",
    summary:
      "Order block, FVG, BOS/CHoCH, likidite süpürme, premium/discount — seans odaklı okuma.",
    howTo: [
      "HTF bias (1h/4h). LTF 5m/15m giriş.",
      "Likidite süpürme → CHoCH → FVG/OB’ye limit.",
      "Killzone: Londra / NY AM pencerelerinde öncelik.",
      "Risk ≤ %0.5–1; OB içine stop koyma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bosChoch", params: { swing: 3 } },
      { type: "orderBlocks", params: { swing: 3, impulseMult: 1.2 } },
      { type: "fairValueGaps", params: { extend: 24 } },
      { type: "liquiditySweep", params: { lookback: 20 } },
      { type: "premiumDiscount", params: { lookback: 50 } },
      { type: "ema", params: { period: 50 }, color: "#90a4ae" },
    ],
    risk: {
      rMultiple: 2.5,
      tip: "Seans dışı zorlama; sweep + yapı teyidi bekle.",
    },
    backtestPreset: "supertrendFlip",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 3 },
    scannerPresets: ["bb_sikisma", "near_lod", "near_hod"],
    tags: ["ICT", "SMC", "FVG", "OB", "YouTube"],
  },
  {
    id: "zscore_regime_pb",
    name: "Z-Score Trend Pullback",
    shortName: "Z-Score",
    category: "mean_reversion",
    inspiredBy: "QQQ-style regime + Z-score dip (community Pine)",
    summary:
      "200 SMA üstü rejimde Z < −1.5 + hızlı MA yukarı kesim → Z≈0 çıkış.",
    howTo: [
      "TF 1d veya 4h (kripto 4h/1d).",
      "Sadece close > SMA200 iken long.",
      "Z eşiği −1.5; çıkış Z > 0. ATR stop opsiyonel.",
      "Backtest’te aynı preset hazır.",
    ],
    timeframe: "1d",
    allowShort: false,
    replaceIndicators: true,
    indicators: [
      { type: "sma", params: { period: 200 }, color: "#42a5f5" },
      { type: "sma", params: { period: 20 }, color: "#ff9800" },
      { type: "ema", params: { period: 5 }, color: "#66bb6a" },
      { type: "bollinger", params: { period: 20, mult: 2 } },
      { type: "rsi", params: { period: 14 } },
    ],
    risk: {
      rMultiple: 1.5,
      tip: "Bear rejimde (200 altı) long yok — paket short kapalı.",
    },
    backtestPreset: "zScorePullback",
    backtestExtras: {
      useAtrStops: false,
      useSignalExits: true,
      fast: 5,
      zLength: 20,
      regimeSMA: 200,
      entryZ: -1.5,
      exitZ: 0,
      allowShort: false,
      warmup: 220,
    },
    scannerPresets: ["multi_mean_rev", "asiri_satim"],
    scannerChips: ["rsi30", "stoch_os"],
    tags: ["Z-Score", "regime", "swing"],
  },
  {
    id: "adx_di_trend",
    name: "ADX + DI± Trend",
    shortName: "ADX·DI",
    category: "trend",
    inspiredBy: "Classic DMI YouTube tutorials (Wilder ADX)",
    summary: "ADX>25 güç + DI+ / DI− kesişim. Zayıf ADX’te işlem yok.",
    howTo: [
      "TF 15m–1h. ADX>25 olunca DI kesişimini bekle.",
      "Long: DI+ ↑ DI−. Short: DI− ↑ DI+.",
      "Çıkış: ters DI kesişim veya ADX < 20.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "adx", params: { period: 14 } },
      { type: "ema", params: { period: 21 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Range’de ADX düşükken zorlama." },
    backtestPreset: "diAdxTrend",
    backtestExtras: {
      useAtrStops: false,
      useSignalExits: true,
      allowShort: true,
      adxMin: 25,
    },
    scannerPresets: ["adx_trend_di_bull", "adx_strong", "di_plus_cross_up"],
    scannerChips: ["di_bull", "adx25"],
    tags: ["ADX", "DMI", "trend"],
  },
  {
    id: "aroon_swing",
    name: "Aroon Long System",
    shortName: "Aroon",
    category: "swing",
    inspiredBy: "Aroon ‘Aaron long’ style community scans",
    summary: "Aroon Up↑Down veya Up>70 / Down<30 zone — swing trend.",
    howTo: [
      "TF 4h / 1d. Aroon Up kesişim veya 70/30 zone.",
      "Çıkış: Down↑Up veya Up < 50.",
      "Tarayıcı preset: Aroon long.",
    ],
    timeframe: "4h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "aroon", params: { period: 14 } },
      { type: "sma", params: { period: 50 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.5, tip: "Swing: pozisyon boyutu küçült." },
    backtestPreset: "aroonLongTrend",
    backtestExtras: { useAtrStops: true, useSignalExits: true, allowShort: true },
    scannerPresets: ["aroon_long", "aroon_long_zone"],
    scannerChips: ["aroon_x", "aroon_zone"],
    tags: ["Aroon", "swing"],
  },
  {
    id: "jurik_os_bounce",
    name: "Jurik Kase OS Bounce",
    shortName: "JKase",
    category: "mean_reversion",
    inspiredBy: "Loxx/Jurik community + TradeDesk Kase Stoch",
    summary: "%K↑%D 15–20 bandında OS bounce; 50 veya ters kesişim çıkış.",
    howTo: [
      "TF 15m–1h. Jurik Kase panelde 15–20 ↑ sinyali.",
      "Trend filtresi için EMA21 ekli.",
      "Tarayıcı: Jurik Kase 15–20 ↑ preset.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "jurikKaseStoch", params: { cycle: 5, kLen: 8, dLen: 3, jmaLen: 5 } },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "Sadece OS/OB bant kesişimleri." },
    backtestPreset: "jurikOsBounce",
    backtestExtras: { useAtrStops: false, useSignalExits: true, allowShort: true },
    scannerPresets: ["jurik_kase_os_up", "jurik_stoch_os_up"],
    scannerChips: ["jkase_os", "jstoch_os"],
    tags: ["Jurik", "stochastic", "OS"],
  },
  {
    id: "bb_mean_rev",
    name: "Bollinger Mean Reversion",
    shortName: "BB MR",
    category: "mean_reversion",
    inspiredBy: "Classic BB fade + RSI (YouTube mean-reversion)",
    summary: "BB alt band + RSI OS long; üst band + RSI OB short/çıkış.",
    howTo: [
      "TF 15m–1h range piyasasında.",
      "Long: kapanış BB alt + RSI<30. Çıkış: orta band / RSI>50.",
      "Trend günlerinde (ADX yüksek) kullanma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bollinger", params: { period: 20, mult: 2 } },
      { type: "rsi", params: { period: 14 } },
      { type: "adx", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.5, tip: "ADX>25 ise mean-rev’i kapat." },
    backtestPreset: "bbBreak",
    backtestExtras: { useAtrStops: true, slAtrMult: 1, tpAtrMult: 1.5 },
    scannerPresets: ["multi_mean_rev", "bb_sikisma"],
    scannerChips: ["rsi30", "bb_sq"],
    tags: ["Bollinger", "RSI", "mean-rev"],
  },
  {
    id: "supertrend_follow",
    name: "Supertrend Follow",
    shortName: "ST",
    category: "trend",
    inspiredBy: "Supertrend flip systems (popular TV/YouTube)",
    summary: "Supertrend yön flip + ATR risk. Sade trend takip.",
    howTo: [
      "TF 15m–4h. Bullish flip → long; bearish flip → short.",
      "Stop: ST çizgisi / ATR×1.5. Trail ile bırak.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "supertrend", params: { period: 10, mult: 3 } },
      { type: "ema", params: { period: 50 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Chop’ta ST kırılımları artar — ADX filtrele." },
    backtestPreset: "supertrendFlip",
    backtestExtras: { useAtrStops: true, stMult: 3, allowShort: true },
    scannerPresets: ["supertrend_long"],
    scannerChips: ["st_b"],
    tags: ["Supertrend", "trend"],
  },
  {
    id: "london_ny_session",
    name: "Londra / NY Killzone Focus",
    shortName: "Killzone",
    category: "session",
    inspiredBy: "ICT killzone timing (London / NY AM)",
    summary:
      "Sadece yüksek likidite pencerelerinde SMC kit + seans disiplini.",
    howTo: [
      "TR (UTC+3): Londra ~10:00–13:00, NY AM ~15:30–18:00.",
      "Bu paneli uygula → SMC göstergeleri gelir.",
      "Pencere dışı setup’ları atla.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bosChoch", params: { swing: 3 } },
      { type: "orderBlocks", params: { swing: 3 } },
      { type: "fairValueGaps", params: { extend: 16 } },
      { type: "liquiditySweep", params: { lookback: 15 } },
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
    ],
    risk: {
      rMultiple: 2,
      tip: "Killzone dışı işlem = kural ihlali say.",
    },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { fast: 9, slow: 21, useAtrStops: true },
    scannerPresets: ["momentum_breakout", "hacim_ema"],
    tags: ["killzone", "ICT", "session"],
  },
];

export function strategyById(id: string): StrategyPack | undefined {
  return STRATEGY_PACKS.find((s) => s.id === id);
}

/** Killzone windows in Europe/Istanbul (UTC+3) — illustrative ICT-style. */
export const KILLZONES_TR = [
  { id: "asia", label: "Asya range", start: "02:00", end: "05:00" },
  { id: "london", label: "Londra KZ", start: "10:00", end: "13:00" },
  { id: "ny_am", label: "NY AM KZ", start: "15:30", end: "18:00" },
  { id: "ny_pm", label: "NY PM / Silver", start: "22:00", end: "23:00" },
] as const;
