import type { StrategyPack } from "./types";

/**
 * One-click playbooks compiled from common retail/YouTube systems
 * (ORB+VWAP, EMA pullback, ICT/SMC, Z-Score, ADX/DI, Aroon, Jurik).
 * Educational packaging — not financial advice / not official affiliations.
 */
export const STRATEGY_PACKS: StrategyPack[] = [
  {
    id: "orb_vwap_momentum",
    name: "ORB + VWAP Momentum",
    shortName: "ORB·VWAP",
    category: "momentum",
    inspiredBy: "Ross Cameron / Warrior-style ORB + VWAP (YouTube day-trading)",
    summary:
      "Açılış aralığı kırılımı + VWAP üstü momentum. 9/20 EMA ‘bone zone’, hacim teyidi.",
    howTo: [
      "TF 5m (veya 1m). İlk 5–15 dk high/low’u işaretle (manuel / formasyon).",
      "Long: fiyat OR high üstü + VWAP üstü + 9 EMA tutuyor.",
      "Stop: VWAP altı veya range low. Hedef: 1–2R, kalanı 9 EMA trail.",
      "Tarayıcı: Crypto gainers / hacim spike ile aday üret.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "ema", params: { period: 20 }, color: "#ff9800" },
      { type: "atr", params: { period: 14 } },
      { type: "volumeOsc", params: { shortPeriod: 5, longPeriod: 10 } },
    ],
    risk: {
      rMultiple: 2,
      tip: "İlk 1–2 saatte kal; 3 arka arkaya stop → günü kapat.",
    },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: {
      fast: 9,
      slow: 20,
      useAtrStops: true,
      slAtrMult: 1.2,
      tpAtrMult: 2,
      allowShort: true,
    },
    scannerPresets: ["crypto_gainers", "hacim_ema", "momentum_breakout"],
    scannerChips: ["vol2", "ema_b"],
    tags: ["ORB", "VWAP", "daytrade", "YouTube"],
  },
  {
    id: "ema_pullback_trend",
    name: "EMA 9/21 Pullback",
    shortName: "EMA PB",
    category: "trend",
    inspiredBy: "Classic YouTube trend-pullback (9/21 EMA ride)",
    summary:
      "Trend yönünde 9/21 EMA pullback. Fiyat EMA’ya iner, tutar, devam.",
    howTo: [
      "TF 15m veya 1h. 9 EMA > 21 EMA = long bias.",
      "Pullback 9 veya 21’e; rejection mum + hacim.",
      "Stop: son swing altı / 21 EMA altı. TP: 1.5–2.5R.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "sma", params: { period: 200 }, color: "#78909c" },
      { type: "rsi", params: { period: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "200 SMA karşıtı pullback’lere dikkat." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 9, slow: 21, useAtrStops: true, allowShort: true },
    scannerPresets: ["multi_long", "macd_bull"],
    scannerChips: ["ema_b", "sma50a"],
    tags: ["EMA", "pullback", "trend"],
  },
  {
    id: "ict_smc_kit",
    name: "ICT / SMC Kit",
    shortName: "SMC",
    category: "smc_ict",
    inspiredBy: "ICT killzones + community SMC (OB, FVG, BOS, liquidity)",
    summary:
      "Order block, FVG, BOS/CHoCH, likidite süpürme, premium/discount — seans odaklı okuma.",
    howTo: [
      "HTF bias (1h/4h). LTF 5m/15m giriş.",
      "Likidite süpürme → CHoCH → FVG/OB’ye limit.",
      "Killzone: Londra / NY AM pencerelerinde öncelik.",
      "Risk ≤ %0.5–1; OB içine stop koyma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bosChoch", params: { swing: 3 } },
      { type: "orderBlocks", params: { swing: 3, impulseMult: 1.2 } },
      { type: "fairValueGaps", params: { extend: 24 } },
      { type: "liquiditySweep", params: { lookback: 20 } },
      { type: "premiumDiscount", params: { lookback: 50 } },
      { type: "ema", params: { period: 50 }, color: "#90a4ae" },
    ],
    risk: {
      rMultiple: 2.5,
      tip: "Seans dışı zorlama; sweep + yapı teyidi bekle.",
    },
    backtestPreset: "supertrendFlip",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 3 },
    scannerPresets: ["bb_sikisma", "near_lod", "near_hod"],
    tags: ["ICT", "SMC", "FVG", "OB", "YouTube"],
  },
  {
    id: "zscore_regime_pb",
    name: "Z-Score Trend Pullback",
    shortName: "Z-Score",
    category: "mean_reversion",
    inspiredBy: "QQQ-style regime + Z-score dip (community Pine)",
    summary:
      "200 SMA üstü rejimde Z < −1.5 + hızlı MA yukarı kesim → Z≈0 çıkış.",
    howTo: [
      "TF 1d veya 4h (kripto 4h/1d).",
      "Sadece close > SMA200 iken long.",
      "Z eşiği −1.5; çıkış Z > 0. ATR stop opsiyonel.",
      "Backtest’te aynı preset hazır.",
    ],
    timeframe: "1d",
    allowShort: false,
    replaceIndicators: true,
    indicators: [
      { type: "sma", params: { period: 200 }, color: "#42a5f5" },
      { type: "sma", params: { period: 20 }, color: "#ff9800" },
      { type: "ema", params: { period: 5 }, color: "#66bb6a" },
      { type: "bollinger", params: { period: 20, mult: 2 } },
      { type: "rsi", params: { period: 14 } },
    ],
    risk: {
      rMultiple: 1.5,
      tip: "Bear rejimde (200 altı) long yok — paket short kapalı.",
    },
    backtestPreset: "zScorePullback",
    backtestExtras: {
      useAtrStops: false,
      useSignalExits: true,
      fast: 5,
      zLength: 20,
      regimeSMA: 200,
      entryZ: -1.5,
      exitZ: 0,
      allowShort: false,
      warmup: 220,
    },
    scannerPresets: ["multi_mean_rev", "asiri_satim"],
    scannerChips: ["rsi30", "stoch_os"],
    tags: ["Z-Score", "regime", "swing"],
  },
  {
    id: "adx_di_trend",
    name: "ADX + DI± Trend",
    shortName: "ADX·DI",
    category: "trend",
    inspiredBy: "Classic DMI YouTube tutorials (Wilder ADX)",
    summary: "ADX>25 güç + DI+ / DI− kesişim. Zayıf ADX’te işlem yok.",
    howTo: [
      "TF 15m–1h. ADX>25 olunca DI kesişimini bekle.",
      "Long: DI+ ↑ DI−. Short: DI− ↑ DI+.",
      "Çıkış: ters DI kesişim veya ADX < 20.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "adx", params: { period: 14 } },
      { type: "ema", params: { period: 21 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Range’de ADX düşükken zorlama." },
    backtestPreset: "diAdxTrend",
    backtestExtras: {
      useAtrStops: false,
      useSignalExits: true,
      allowShort: true,
      adxMin: 25,
    },
    scannerPresets: ["adx_trend_di_bull", "adx_strong", "di_plus_cross_up"],
    scannerChips: ["di_bull", "adx25"],
    tags: ["ADX", "DMI", "trend"],
  },
  {
    id: "aroon_swing",
    name: "Aroon Long System",
    shortName: "Aroon",
    category: "swing",
    inspiredBy: "Aroon ‘Aaron long’ style community scans",
    summary: "Aroon Up↑Down veya Up>70 / Down<30 zone — swing trend.",
    howTo: [
      "TF 4h / 1d. Aroon Up kesişim veya 70/30 zone.",
      "Çıkış: Down↑Up veya Up < 50.",
      "Tarayıcı preset: Aroon long.",
    ],
    timeframe: "4h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "aroon", params: { period: 14 } },
      { type: "sma", params: { period: 50 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.5, tip: "Swing: pozisyon boyutu küçült." },
    backtestPreset: "aroonLongTrend",
    backtestExtras: { useAtrStops: true, useSignalExits: true, allowShort: true },
    scannerPresets: ["aroon_long", "aroon_long_zone"],
    scannerChips: ["aroon_x", "aroon_zone"],
    tags: ["Aroon", "swing"],
  },
  {
    id: "jurik_os_bounce",
    name: "Jurik Kase OS Bounce",
    shortName: "JKase",
    category: "mean_reversion",
    inspiredBy: "Loxx/Jurik community + TradeDesk Kase Stoch",
    summary: "%K↑%D 15–20 bandında OS bounce; 50 veya ters kesişim çıkış.",
    howTo: [
      "TF 15m–1h. Jurik Kase panelde 15–20 ↑ sinyali.",
      "Trend filtresi için EMA21 ekli.",
      "Tarayıcı: Jurik Kase 15–20 ↑ preset.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "jurikKaseStoch", params: { cycle: 5, kLen: 8, dLen: 3, jmaLen: 5 } },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "Sadece OS/OB bant kesişimleri." },
    backtestPreset: "jurikOsBounce",
    backtestExtras: { useAtrStops: false, useSignalExits: true, allowShort: true },
    scannerPresets: ["jurik_kase_os_up", "jurik_stoch_os_up"],
    scannerChips: ["jkase_os", "jstoch_os"],
    tags: ["Jurik", "stochastic", "OS"],
  },
  {
    id: "bb_mean_rev",
    name: "Bollinger Mean Reversion",
    shortName: "BB MR",
    category: "mean_reversion",
    inspiredBy: "Classic BB fade + RSI (YouTube mean-reversion)",
    summary: "BB alt band + RSI OS long; üst band + RSI OB short/çıkış.",
    howTo: [
      "TF 15m–1h range piyasasında.",
      "Long: kapanış BB alt + RSI<30. Çıkış: orta band / RSI>50.",
      "Trend günlerinde (ADX yüksek) kullanma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bollinger", params: { period: 20, mult: 2 } },
      { type: "rsi", params: { period: 14 } },
      { type: "adx", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.5, tip: "ADX>25 ise mean-rev’i kapat." },
    backtestPreset: "bbBreak",
    backtestExtras: { useAtrStops: true, slAtrMult: 1, tpAtrMult: 1.5 },
    scannerPresets: ["multi_mean_rev", "bb_sikisma"],
    scannerChips: ["rsi30", "bb_sq"],
    tags: ["Bollinger", "RSI", "mean-rev"],
  },
  {
    id: "supertrend_follow",
    name: "Supertrend Follow",
    shortName: "ST",
    category: "trend",
    inspiredBy: "Supertrend flip systems (popular TV/YouTube)",
    summary: "Supertrend yön flip + ATR risk. Sade trend takip.",
    howTo: [
      "TF 15m–4h. Bullish flip → long; bearish flip → short.",
      "Stop: ST çizgisi / ATR×1.5. Trail ile bırak.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "supertrend", params: { period: 10, mult: 3 } },
      { type: "ema", params: { period: 50 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Chop’ta ST kırılımları artar — ADX filtrele." },
    backtestPreset: "supertrendFlip",
    backtestExtras: { useAtrStops: true, stMult: 3, allowShort: true },
    scannerPresets: ["supertrend_long"],
    scannerChips: ["st_b"],
    tags: ["Supertrend", "trend"],
  },
  {
    id: "london_ny_session",
    name: "Londra / NY Killzone Focus",
    shortName: "Killzone",
    category: "session",
    inspiredBy: "ICT killzone timing (London / NY AM)",
    summary:
      "Sadece yüksek likidite pencerelerinde SMC kit + seans disiplini.",
    howTo: [
      "TR (UTC+3): Londra ~10:00–13:00, NY AM ~15:30–18:00.",
      "Bu paneli uygula → SMC göstergeleri gelir.",
      "Pencere dışı setup’ları atla.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bosChoch", params: { swing: 3 } },
      { type: "orderBlocks", params: { swing: 3 } },
      { type: "fairValueGaps", params: { extend: 16 } },
      { type: "liquiditySweep", params: { lookback: 15 } },
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
    ],
    risk: {
      rMultiple: 2,
      tip: "Killzone dışı işlem = kural ihlali say.",
    },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { fast: 9, slow: 21, useAtrStops: true },
    scannerPresets: ["momentum_breakout", "hacim_ema"],
    tags: ["killzone", "ICT", "session"],
  },

  // ——— 5 / 10 / 15 dk odaklı (araştırılmış ayarlar) ———
  {
    id: "m5_macd_vwap_scalp",
    name: "5m MACD 5-13-1 + VWAP",
    shortName: "5m MACD",
    category: "momentum",
    inspiredBy: "Intraday MACD 5-13-1 (SMC Trade Online) + VWAP filter",
    summary:
      "5 dk scalp: hızlı MACD (5,13,1) + VWAP yön + EMA9. Varsayılan 12-26-9 yerine optimize.",
    howTo: [
      "TF 5m. Long: fiyat VWAP üstü + MACD çizgisi sinyal üstü kesişim + hist genişliyor.",
      "EMA9 altında kapanışlarda long alma.",
      "Hold ~15–60 dk. Stop ATR×1.0–1.2, TP 1.5–2R.",
      "Backtest: MACD Cross (5/13/1 ayarlı).",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "macd", params: { fast: 5, slow: 13, signal: 1 }, color: "#2962ff" },
      { type: "atr", params: { period: 14 } },
      { type: "rsi", params: { period: 14 } },
    ],
    risk: {
      rMultiple: 1.8,
      tip: "Range’de MACD gürültülü — VWAP filtresini bozma.",
    },
    backtestPreset: "macdCross",
    backtestExtras: {
      macdFast: 5,
      macdSlow: 13,
      macdSignal: 1,
      useAtrStops: true,
      slAtrMult: 1.1,
      tpAtrMult: 1.8,
      allowShort: true,
      warmup: 40,
    },
    scannerPresets: ["macd_bull", "hacim_ema"],
    scannerChips: ["macd_b", "vol2"],
    tags: ["5m", "MACD", "VWAP", "scalp"],
  },
  {
    id: "m5_macd_aggressive",
    name: "5m MACD 3-10-1 Aggressive",
    shortName: "5m MACD↑",
    category: "momentum",
    inspiredBy: "Aggressive 5m MACD 3-10-1 scalping settings",
    summary:
      "Çok hızlı MACD (3,10,1) + EMA 8/21 stack. Kısa tutuş, yüksek gürültü.",
    howTo: [
      "TF 5m. Sadece EMA8 > EMA21 iken long MACD↑.",
      "Çıkış: MACD ters kesişim veya EMA8 kırılımı.",
      "3 arka arkaya stop → mola.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ema", params: { period: 8 }, color: "#26a69a" },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "macd", params: { fast: 3, slow: 10, signal: 1 } },
      { type: "volumeOsc", params: { shortPeriod: 5, longPeriod: 10 } },
    ],
    risk: { rMultiple: 1.5, tip: "Agresif — size küçük tut." },
    backtestPreset: "macdCross",
    backtestExtras: {
      macdFast: 3,
      macdSlow: 10,
      macdSignal: 1,
      fast: 8,
      slow: 21,
      useAtrStops: true,
      slAtrMult: 1,
      tpAtrMult: 1.5,
      allowShort: true,
    },
    scannerPresets: ["momentum_breakout", "macd_bull"],
    tags: ["5m", "MACD", "scalp", "aggressive"],
  },
  {
    id: "m5_orb_vwap_strict",
    name: "5m ORB + 9/20 EMA + VWAP",
    shortName: "5m ORB",
    category: "session",
    inspiredBy: "5-minute opening range (Edgeful/ORB guides) + Warrior EMA/VWAP",
    summary:
      "İlk 5 dk range kırılımı; teyit VWAP + 9/20 EMA bone zone. Stop range karşı kenar.",
    howTo: [
      "Seans açılışı sonrası ilk 5m mum high/low = OR.",
      "Long: OR high kırılımı + close > VWAP + 9 EMA ≥ 20 EMA.",
      "Stop: OR low (veya VWAP). TP: range’in %50–100’ü / 1.5R.",
      "Geniş OR günlerinde (çok volatil) işlem atla.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "ema", params: { period: 20 }, color: "#ff9800" },
      { type: "atr", params: { period: 14 } },
      { type: "highVolumePoints", params: { volMult: 2, swing: 2 } },
    ],
    risk: {
      rMultiple: 1.5,
      tip: "İlk 90 dk; öğleden sonra ORB’yi zorlama.",
    },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: {
      fast: 9,
      slow: 20,
      useAtrStops: true,
      slAtrMult: 1.2,
      tpAtrMult: 1.8,
      allowShort: true,
    },
    scannerPresets: ["crypto_gainers", "momentum_breakout"],
    scannerChips: ["vol2", "ema_b"],
    tags: ["5m", "ORB", "VWAP", "session"],
  },
  {
    id: "m5_stoch_vwap_bounce",
    name: "5m Stoch OS + VWAP",
    shortName: "5m Stoch",
    category: "mean_reversion",
    inspiredBy: "Stochastic 14-3-3 OS bounce with VWAP (intraday)",
    summary:
      "Stoch %K↑%D 20 altı + fiyat VWAP’a yakın / üstünde bounce.",
    howTo: [
      "TF 5m. Long: Stoch K↑D ve K≤25, close ≥ VWAP×0.998.",
      "Çıkış: K>50 veya VWAP altı kapanış.",
      "Güçlü downtrend’de (EMA21 düşen) short tarafını tercih et.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "stochastic", params: { kPeriod: 14, dPeriod: 3 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.5, tip: "Chop’ta Stoch çok sinyal üretir — VWAP şart." },
    backtestPreset: "rsiOsOb",
    backtestExtras: {
      rsiOs: 30,
      useAtrStops: true,
      slAtrMult: 1,
      tpAtrMult: 1.5,
      allowShort: true,
    },
    scannerPresets: ["stoch_os_cross_up", "asiri_satim"],
    scannerChips: ["stoch_x_up", "stoch_os"],
    tags: ["5m", "Stochastic", "VWAP"],
  },
  {
    id: "m10_ema_rsi_momentum",
    name: "10m EMA 8/21 + RSI 40/60",
    shortName: "10m EMA",
    category: "trend",
    inspiredBy: "AlphaX-style RSI 40/60 momentum + EMA 8/21 (gold/intraday)",
    summary:
      "10 dk (5m×2 agg): EMA8/21 trend + RSI14 eşik 40/60 (30/70 değil).",
    howTo: [
      "TF 10m. Long: EMA8>21 ve RSI>50 (ideal >60 devam).",
      "Pullback: RSI 40–50’ye iner, EMA8 tutar → ekleme.",
      "Çıkış: EMA8<21 veya RSI<40.",
    ],
    timeframe: "10m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ema", params: { period: 8 }, color: "#26a69a" },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "ema", params: { period: 55 }, color: "#78909c" },
      { type: "rsi", params: { period: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: {
      rMultiple: 2,
      tip: "RSI 40/60 momentum eşiği — klasik 30/70’ten erken.",
    },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: {
      fast: 8,
      slow: 21,
      rsiOs: 40,
      rsiOb: 60,
      useAtrStops: true,
      slAtrMult: 1.3,
      tpAtrMult: 2.2,
      allowShort: true,
      warmup: 60,
    },
    scannerPresets: ["multi_long", "macd_bull"],
    scannerChips: ["ema_b", "rsi30"],
    tags: ["10m", "EMA", "RSI", "momentum"],
  },
  {
    id: "m10_vwap_macd",
    name: "10m VWAP + MACD 5-13-1",
    shortName: "10m VWAP",
    category: "momentum",
    inspiredBy: "VWAP institutional + faster MACD for mid-scalp",
    summary: "10m: VWAP yön filtresi + MACD 5-13-1 giriş. İki araç birlikte.",
    howTo: [
      "Long yalnızca close > VWAP iken MACD↑.",
      "Short: close < VWAP + MACD↓.",
      "Stop: VWAP’ın diğer yanı veya ATR×1.2.",
    ],
    timeframe: "10m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "macd", params: { fast: 5, slow: 13, signal: 1 } },
      { type: "ema", params: { period: 20 }, color: "#ff9800" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "VWAP ortasında (yapışık) bekle — net taraf seç." },
    backtestPreset: "macdCross",
    backtestExtras: {
      macdFast: 5,
      macdSlow: 13,
      macdSignal: 1,
      useAtrStops: true,
      slAtrMult: 1.2,
      tpAtrMult: 1.8,
      allowShort: true,
    },
    scannerPresets: ["macd_bull", "hacim_ema"],
    tags: ["10m", "VWAP", "MACD"],
  },
  {
    id: "m15_stochrsi_macd",
    name: "15m StochRSI + MACD",
    shortName: "15m SRSI",
    category: "momentum",
    inspiredBy: "Stochastic RSI + MACD confluence (15m recommended vs 5m noise)",
    summary:
      "15m: StochRSI K↑D (K<50 filtresi) + MACD 12-26-9 teyit. İki osilatör birlikte.",
    howTo: [
      "TF 15m. Long: StochRSI K↑D ve K<50 + MACD çizgisi > sinyal (veya yeni↑).",
      "Short: K↓D ve K>50 + MACD↓.",
      "5m’de gürültü yüksek — bu paket bilerek 15m.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "stochRsi", params: { rsiPeriod: 14, stochPeriod: 14, kSmooth: 3, dSmooth: 3 } },
      { type: "macd", params: { fast: 12, slow: 26, signal: 9 } },
      { type: "ema", params: { period: 50 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "EMA50 karşıtı sinyalleri ele." },
    backtestPreset: "macdCross",
    backtestExtras: {
      macdFast: 12,
      macdSlow: 26,
      macdSignal: 9,
      useAtrStops: true,
      slAtrMult: 1.4,
      tpAtrMult: 2.2,
      allowShort: true,
    },
    scannerPresets: ["macd_bull", "stoch_os_cross_up"],
    scannerChips: ["macd_b", "stoch_x_up"],
    tags: ["15m", "StochRSI", "MACD"],
  },
  {
    id: "m15_vwap_ema_pullback",
    name: "15m VWAP + EMA9/21 Pullback",
    shortName: "15m VWAP PB",
    category: "trend",
    inspiredBy: "YouTube day-trade pullback: VWAP hold + 9/21 EMA",
    summary:
      "15m trend: VWAP üstü bias, pullback 9 veya 21 EMA’ya, rejection ile giriş.",
    howTo: [
      "Bias: close > VWAP ve EMA9 > EMA21.",
      "Giriş: pullback EMA9/21’e + hacimli yeşil mum.",
      "Stop: EMA21 altı veya VWAP. Trail 9 EMA.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vwap", color: "#e040fb" },
      { type: "ema", params: { period: 9 }, color: "#26a69a" },
      { type: "ema", params: { period: 21 }, color: "#42a5f5" },
      { type: "volumeOsc", params: { shortPeriod: 5, longPeriod: 10 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Öğle sakinliğinde pullback’ler uzar — sabır." },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: {
      fast: 9,
      slow: 21,
      useAtrStops: true,
      slAtrMult: 1.3,
      tpAtrMult: 2.5,
      allowShort: true,
    },
    scannerPresets: ["hacim_ema", "multi_long"],
    scannerChips: ["ema_b", "vol2"],
    tags: ["15m", "VWAP", "EMA", "pullback"],
  },
  {
    id: "m15_bb_squeeze_break",
    name: "15m BB Squeeze → Break",
    shortName: "15m BB Sq",
    category: "momentum",
    inspiredBy: "Bollinger squeeze breakout (TV/YouTube compression→expansion)",
    summary:
      "BB sıkışma sonrası kırılım; ADX güç filtresi + BB Width. İki ölçüm: BB + ADX.",
    howTo: [
      "TF 15m. Width daralınca izle; close üst/alt band kırılımı.",
      "ADX>20 (ideal >25) olmadan kırma peşinden koşma.",
      "Stop: mid band. TP: 1.5–2× sıkışma genişliği / ATR.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "bollinger", params: { period: 20, mult: 2 } },
      { type: "bbWidth", params: { period: 20, mult: 2 } },
      { type: "adx", params: { period: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Sahte kırılımlar sık — kapanış teyidi bekle." },
    backtestPreset: "bbBreak",
    backtestExtras: {
      bbPeriod: 20,
      bbMult: 2,
      useAtrStops: true,
      slAtrMult: 1.2,
      tpAtrMult: 2,
      allowShort: true,
    },
    scannerPresets: ["bb_sikisma", "momentum_breakout", "adx_strong"],
    scannerChips: ["bb_sq", "bb_up", "adx25"],
    tags: ["15m", "Bollinger", "ADX", "squeeze"],
  },
  {
    id: "m5_supertrend_fast",
    name: "5m Supertrend 7/2 Fast",
    shortName: "5m ST",
    category: "trend",
    inspiredBy: "Faster Supertrend for scalps (period 7, mult 2) vs classic 10/3",
    summary:
      "5m scalp Supertrend 7×2 + EMA20 filtre. Klasik 10/3’ten daha hızlı flip.",
    howTo: [
      "Long: ST bullish flip ve close > EMA20.",
      "Stop: ST çizgisi. Flip olunca tersine bak veya çık.",
      "Chop’ta sık flip — ADX opsiyonel ekleyebilirsin.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "supertrend", params: { period: 7, mult: 2 } },
      { type: "ema", params: { period: 20 }, color: "#42a5f5" },
      { type: "atr", params: { period: 14 } },
      { type: "adx", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.6, tip: "ADX<20 iken ST flip’lerini atla." },
    backtestPreset: "supertrendFlip",
    backtestExtras: {
      atrPeriod: 7,
      stMult: 2,
      useAtrStops: true,
      slAtrMult: 1,
      tpAtrMult: 1.6,
      allowShort: true,
    },
    scannerPresets: ["supertrend_long", "adx_strong"],
    scannerChips: ["st_b", "adx25"],
    tags: ["5m", "Supertrend", "scalp"],
  },

  // ——— Az bilinen / niş araçlar ———
  {
    id: "niche_qqe_jma",
    name: "QQE 14×4.236 + JMA",
    shortName: "QQE·JMA",
    category: "niche",
    inspiredBy: "Classic QQE (RSI14, smooth5, factor 4.236) + Jurik JMA trend",
    summary:
      "QQE trailing-level kesişim (LuxAlgo/klasik) + JMA(14) yön. RSI’dan daha az flip.",
    howTo: [
      "TF 15m. Long: QQE çizgisi trailing üstü + fiyat JMA üstü.",
      "Short: QQE trailing altı + fiyat JMA altı.",
      "50 hattı filtresi: QQE >50 iken long’a öncelik.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "jurikQqe", params: { rsiLen: 14, jmaLen: 8, smoothLen: 5, qqeFactor: 4.236, phase: 50 } },
      { type: "jma", params: { period: 14, phase: 50, power: 2 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "QQE onay aracıdır — kovalama, kesişim bekle." },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { fast: 9, slow: 21, useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2.2 },
    tags: ["QQE", "Jurik", "niche", "15m"],
  },
  {
    id: "niche_vortex_chandelier",
    name: "Vortex + Chandelier Exit",
    shortName: "VI·CE",
    category: "niche",
    inspiredBy: "Vortex Indicator crossover + Chandelier trailing (Wilder-style)",
    summary: "VI+ / VI− kesişim giriş; Chandelier Exit (22,3) trail stop çizgisi.",
    howTo: [
      "TF 15m–1h. Long: VI+ ↑ VI−. Stop/trail: Chandelier long çizgisi.",
      "Short: VI− ↑ VI+. Trail: Chandelier short.",
      "Period 14 Vortex standart.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vortex", params: { period: 14 } },
      { type: "chandelier", params: { period: 22, mult: 3 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.5, tip: "Chandelier trail’i manuel izle — kırılınca çık." },
    backtestPreset: "diAdxTrend",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 2.5, allowShort: true },
    tags: ["Vortex", "Chandelier", "niche", "15m"],
  },
  {
    id: "niche_fisher_keltner",
    name: "Fisher Transform + Keltner",
    shortName: "Fisher·KC",
    category: "niche",
    inspiredBy: "Ehlers Fisher Transform turn + Keltner channel context",
    summary: "Fisher(10) sıfır/sinyal dönüşü + Keltner(20,1.5) kırılım/geri çekilme.",
    howTo: [
      "TF 15m. Long: Fisher↑ sıfır üstü + fiyat Keltner mid üstü.",
      "Aşırı Fisher (>2) kovalama; pullback mid’e bekle.",
      "Stop: Keltner alt band.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "fisher", params: { period: 10 } },
      { type: "keltner", params: { period: 20, mult: 1.5 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "Fisher uçlarda mean-rev; orta bant trend." },
    backtestPreset: "bbBreak",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 1.8 },
    tags: ["Fisher", "Keltner", "Ehlers", "niche", "15m"],
  },
  {
    id: "niche_connors_mcginley",
    name: "Connors RSI + McGinley",
    shortName: "CRSI·McG",
    category: "niche",
    inspiredBy: "Connors RSI (3,2,100) mean-reversion + McGinley Dynamic",
    summary: "CRSI <10 long / >90 short tarzı aşırı; McGinley(14) trend filtresi.",
    howTo: [
      "TF 15m–1h. Long: CRSI <10–15 ve fiyat McGinley’e yakın/üstü rebound.",
      "Short: CRSI >85–90.",
      "Güçlü trendde (fiyat McG’den uzak) CRSI sinyalini atla.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "connorsRsi", params: { rsiPeriod: 3, streakPeriod: 2, pctRankPeriod: 100 } },
      { type: "mcginley", params: { period: 14 }, color: "#ab47bc" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.5, tip: "Connors aşırı nadir — sabır; size küçük." },
    backtestPreset: "rsiOsOb",
    backtestExtras: { rsiOs: 15, rsiOb: 85, useAtrStops: true, slAtrMult: 1.1, tpAtrMult: 1.5 },
    tags: ["ConnorsRSI", "McGinley", "niche", "15m"],
  },
  {
    id: "niche_tsi_force",
    name: "TSI + Elder Force Index",
    shortName: "TSI·EFI",
    category: "niche",
    inspiredBy: "True Strength Index (25,13,7) + Elder Force Index(13)",
    summary: "TSI sinyal kesişimi + Force Index hacim-momentum teyidi.",
    howTo: [
      "TF 15m. Long: TSI↑sinyal ve Force Index >0 (veya↑0).",
      "Short: TSI↓sinyal ve FI <0.",
      "TSI sıfır altındayken long zayıf kalır — filtrele.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "tsi", params: { longPeriod: 25, shortPeriod: 13, signalPeriod: 7 } },
      { type: "forceIndex", params: { period: 13 } },
      { type: "ema", params: { period: 34 }, color: "#78909c" },
    ],
    risk: { rMultiple: 2, tip: "İki onay yoksa işlem yok." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2 },
    tags: ["TSI", "ForceIndex", "Elder", "niche", "15m"],
  },
  {
    id: "niche_klinger_cmf",
    name: "Klinger + CMF",
    shortName: "KVO·CMF",
    category: "niche",
    inspiredBy: "Klinger Volume Oscillator (34/55/13) + Chaikin Money Flow(20)",
    summary: "Klinger sinyal kesişimi + CMF>0 para akışı teyidi (hacim niş).",
    howTo: [
      "TF 15m–1h. Long: KVO↑sinyal (tercihen 0 altından) + CMF>0.",
      "Short: KVO↓sinyal + CMF<0.",
      "CMF nötrken Klinger’i yalnız kullanma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "klinger", params: { fast: 34, slow: 55, signal: 13 } },
      { type: "cmf", params: { period: 20 } },
      { type: "vwap", color: "#e040fb" },
    ],
    risk: { rMultiple: 2, tip: "Hacimsiz paritede Klinger zayıf — likit sembol seç." },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.4, tpAtrMult: 2.2 },
    scannerPresets: ["hacim_ema"],
    scannerChips: ["vol2"],
    tags: ["Klinger", "CMF", "volume", "niche", "15m"],
  },
  {
    id: "niche_wavetrend_alma",
    name: "WaveTrend + ALMA",
    shortName: "WT·ALMA",
    category: "niche",
    inspiredBy: "LazyBear WaveTrend (10,21) + ALMA(9,0.85,6)",
    summary: "WT1/WT2 kesişim OS/OB bölgelerinde + ALMA trend filtresi.",
    howTo: [
      "TF 5m–15m. Long: WT1↑WT2 ve WT oversold (~−60) civarı + fiyat ALMA üstü.",
      "Short: WT1↓WT2 overbought (~+60) + fiyat ALMA altı.",
      "Kanal 10 / Avg 21 LazyBear varsayılanı.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "wavetrend", params: { channelLen: 10, avgLen: 21 } },
      { type: "alma", params: { period: 9, offset: 0.85, sigma: 6 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "WT uçlardan dönüş; mid-range kesişimleri atla." },
    backtestPreset: "rsiOsOb",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 1.8, allowShort: true },
    tags: ["WaveTrend", "ALMA", "niche", "5m"],
  },
  {
    id: "niche_bill_williams",
    name: "Alligator + AO + Fractals",
    shortName: "BW Pack",
    category: "niche",
    inspiredBy: "Bill Williams: Alligator (13/8/5) + Awesome Oscillator + Fractals",
    summary: "Alligator açılımı + AO renk/sıfır + fractal giriş — klasik BW seti.",
    howTo: [
      "TF 15m. Long: Lips>Teeth>Jaw (açık alligator) + AO>0 yeşil + up fractal kırılımı.",
      "Alligator kapalıyken (çizgiler dolanık) işlem yok.",
      "Stop: son down fractal / Jaw altı.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "alligator", params: { jawPeriod: 13, teethPeriod: 8, lipsPeriod: 5 } },
      { type: "awesomeOsc" },
      { type: "acceleratorOsc" },
      { type: "fractals" },
      { type: "gator" },
    ],
    risk: { rMultiple: 2, tip: "Sleeping alligator = bekle; uyanınca chase etme." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 5, slow: 8, useAtrStops: true, allowShort: true },
    tags: ["BillWilliams", "Alligator", "AO", "niche", "15m"],
  },
  {
    id: "niche_ichimoku_classic",
    name: "Ichimoku 9/26/52 Classic",
    shortName: "Ichimoku",
    category: "niche",
    inspiredBy: "Classic Ichimoku cloud (Tenkan9 Kijun26 Senkou52)",
    summary: "Bulut üstü/altı bias + Tenkan/Kijun kesişim + Chikou teyit.",
    howTo: [
      "TF 15m–1h. Long: fiyat bulut üstü + Tenkan↑Kijun + Chikou fiyat üstü.",
      "Kijun bounce pullback girişi yaygın.",
      "Stop: Kijun veya bulut karşı kenarı.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ichimoku", params: { tenkan: 9, kijun: 26, senkou: 52 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.5, tip: "Bulut içinde (Kumo) işlem açma." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 9, slow: 26, useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 2.5 },
    tags: ["Ichimoku", "niche", "15m"],
  },
  {
    id: "niche_jurik_rsx_voltix",
    name: "Jurik RSX + Voltix Bands",
    shortName: "RSX·Voltix",
    category: "niche",
    inspiredBy: "Jurik RSX momentum + BigBeluga Voltix-like bands",
    summary: "RSX aşırı/dönüş + Voltix bant kırılımı — Jurik+Beluga ikilisi.",
    howTo: [
      "TF 15m. Long: RSX OS’tan yukarı + fiyat Voltix mid/üst yönünde.",
      "Short: RSX OB’tan aşağı + mid altı.",
      "Phase 50 / power 2 Jurik varsayılanı.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "jurikRsx", params: { period: 14, phase: 50, power: 2 } },
      { type: "voltixBands", params: { period: 20, mult: 1.8, phase: 50 } },
      { type: "jurikVolty", params: { period: 20 } },
    ],
    risk: { rMultiple: 2, tip: "Voltix sıkışmada bekle; genişlemede kırılım." },
    backtestPreset: "jurikOsBounce",
    backtestExtras: { useSignalExits: true, useAtrStops: false, allowShort: true },
    scannerPresets: ["jurik_stoch_os_up"],
    tags: ["Jurik", "RSX", "Voltix", "niche", "15m"],
  },
  {
    id: "niche_beluga_flow",
    name: "Nautilus Momentum + Flow Trend",
    shortName: "Beluga Flow",
    category: "niche",
    inspiredBy: "BigBeluga-style Nautilus momentum + Flow Trend + MFC",
    summary: "Beluga osilatör üçlüsü: Nautilus-like + Flow + Money Flow Composite.",
    howTo: [
      "TF 5m–15m. Long: Nautilus↑ + Flow Trend pozitif + MFC>0.",
      "Üçü hizalanmadan girme.",
      "SMC kit ile birleştirilebilir (ayrı paket).",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "nautilusLike", params: { period: 14, smooth: 5 } },
      { type: "flowTrend", params: { period: 14 } },
      { type: "moneyFlowComposite", params: { period: 14 } },
      { type: "ema", params: { period: 21 }, color: "#78909c" },
    ],
    risk: { rMultiple: 1.8, tip: "Confluence şart — tek osilatöre güvenme." },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { fast: 9, slow: 21, useAtrStops: true, allowShort: true },
    tags: ["BigBeluga", "Nautilus", "Flow", "niche", "5m"],
  },
  {
    id: "niche_proreal_adaptive",
    name: "Adaptive SuperTrend + Quality Trail",
    shortName: "PRT Adapt",
    category: "niche",
    inspiredBy: "ProRealCode-style Adaptive SuperTrend + Quality Trend Trail",
    summary: "PRT Adaptive ST giriş + Quality Trail çıkış/trail — iki özel trend aracı.",
    howTo: [
      "TF 15m. Adaptive ST flip = yön. Quality Trail kırılımı = çıkış.",
      "Asym envelope isteğe bağlı volatilite çerçevesi.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "adaptiveSupertrend", params: { atrLen: 10, baseMult: 2, lookback: 50 } },
      { type: "qualityTrendTrail", params: { atrLen: 14, mult: 2.5, qualLen: 20 } },
      { type: "asymVolEnvelope", params: { period: 20, upMult: 2, dnMult: 2 } },
    ],
    risk: { rMultiple: 2.2, tip: "Trail kırılınca hemen flat." },
    backtestPreset: "supertrendFlip",
    backtestExtras: { atrPeriod: 10, stMult: 2, useAtrStops: true, allowShort: true },
    tags: ["ProReal", "AdaptiveST", "niche", "15m"],
  },
  {
    id: "niche_uo_williams",
    name: "Ultimate Osc + Williams %R",
    shortName: "UO·%R",
    category: "niche",
    inspiredBy: "Ultimate Oscillator (7/14/28) + Williams %R(14)",
    summary: "UO divergence/eşik + %R −80/−20 zone — Larry Williams ikilisi.",
    howTo: [
      "TF 15m. Long: UO <30’dan yukarı + %R −80’den yukarı kesişim.",
      "Short: UO >70’ten aşağı + %R −20’den aşağı.",
      "İkisi aynı barda hizalanmazsa bekle.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ultimateOsc", params: { p1: 7, p2: 14, p3: 28 } },
      { type: "williamsR", params: { period: 14 } },
      { type: "sma", params: { period: 50 }, color: "#78909c" },
    ],
    risk: { rMultiple: 1.8, tip: "Çift OS/OB teyidi olmadan girme." },
    backtestPreset: "rsiOsOb",
    backtestExtras: { rsiOs: 30, rsiOb: 70, useAtrStops: true },
    tags: ["UltimateOsc", "WilliamsR", "niche", "15m"],
  },
  {
    id: "niche_kst_donchian",
    name: "KST + Donchian",
    shortName: "KST·DC",
    category: "niche",
    inspiredBy: "Know Sure Thing momentum + Donchian(20) breakout",
    summary: "KST sinyal kesişimi + Donchian kanal kırılımı — momentum+kanal.",
    howTo: [
      "TF 15m–1h. Long: KST↑sinyal ve close Donchian üst bandı kırıyor/üstünde.",
      "Short: KST↓ + alt band kırılımı.",
      "Donchian mid trail olarak kullanılabilir.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "kst", params: { sig: 9 } },
      { type: "donchian", params: { period: 20 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "KST yavaştır — kırılımı KST ile doğrula." },
    backtestPreset: "bbBreak",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.4, tpAtrMult: 2.2 },
    tags: ["KST", "Donchian", "niche", "15m"],
  },
  {
    id: "niche_zlema_trix",
    name: "ZLEMA + TRIX",
    shortName: "ZLEMA·TRIX",
    category: "niche",
    inspiredBy: "Zero-Lag EMA trend + TRIX(18) momentum cross",
    summary: "ZLEMA(20) yön + TRIX sıfır/sinyal — lag’i azaltılmış ikili.",
    howTo: [
      "TF 5m–15m. Long: fiyat ZLEMA üstü + TRIX↑0 veya sinyal üstü.",
      "Short: ZLEMA altı + TRIX↓.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "zlema", params: { period: 20 }, color: "#26a69a" },
      { type: "trix", params: { period: 18 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "ZLEMA hızlıdır — whipsaw’da size küçült." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 10, slow: 20, useAtrStops: true, allowShort: true },
    tags: ["ZLEMA", "TRIX", "niche", "5m"],
  },

  // ——— Az bilinen genişletme (registry niş araçları) ———
  {
    id: "niche_schaff_hma",
    name: "Schaff Trend Cycle + Hull MA",
    shortName: "STC·HMA",
    category: "niche",
    inspiredBy: "Doug Schaff STC (10/23/50) + Alan Hull HMA(21) trend filter",
    summary:
      "STC 25/75 zone dönüşleri + HMA yön filtresi — MACD'den daha az lag'li cycle.",
    howTo: [
      "TF 15m. Long: STC <25'ten yukarı kesişim + fiyat HMA üstü.",
      "Short: STC >75'ten aşağı + fiyat HMA altı.",
      "STC mid-range (40–60) sinyallerini atla.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "schaffTrendCycle", params: { period: 10, fast: 23, slow: 50 } },
      { type: "hma", params: { period: 21 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "STC uç zone + HMA hizası şart; mid kesişim yok." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2.2, allowShort: true },
    tags: ["Schaff", "STC", "HMA", "niche", "15m"],
  },
  {
    id: "niche_rvi_psar",
    name: "RVI + Parabolic SAR",
    shortName: "RVI·PSAR",
    category: "niche",
    inspiredBy: "Relative Vigor Index (10) signal cross + Wilder Parabolic SAR trail",
    summary: "RVI sinyal kesişimi giriş; PSAR noktaları trail/stop — vigor+SAR ikilisi.",
    howTo: [
      "TF 15m–1h. Long: RVI↑sinyal ve fiyat PSAR üstü.",
      "Short: RVI↓sinyal ve fiyat PSAR altı.",
      "PSAR flip = zorunlu flat / ters yön değerlendir.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "rvi", params: { period: 10 } },
      { type: "psar", params: { step: 0.02, max: 0.2 } },
      { type: "ema", params: { period: 50 }, color: "#78909c" },
    ],
    risk: { rMultiple: 2, tip: "PSAR chop'ta sık flip — ADX/EMA50 filtresi ekle." },
    backtestPreset: "supertrendFlip",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.4, tpAtrMult: 2.2, allowShort: true },
    tags: ["RVI", "PSAR", "niche", "15m"],
  },
  {
    id: "niche_elder_impulse_pvt",
    name: "Elder Impulse + PVT",
    shortName: "EI·PVT",
    category: "niche",
    inspiredBy: "Alexander Elder Impulse System (EMA13+MACD) + Price Volume Trend",
    summary: "Elder Impulse yeşil/kırmızı bar + PVT eğim — momentum+hacim teyidi.",
    howTo: [
      "TF 15m. Long: Impulse yeşil (bull) + PVT yükselen eğim.",
      "Short: Impulse kırmızı + PVT düşen.",
      "Mavi (nötr) Impulse'ta yeni pozisyon açma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "elderImpulse", params: { emaLen: 13, macdFast: 12, macdSlow: 26, macdSig: 9 } },
      { type: "pvt" },
      { type: "ema", params: { period: 13 }, color: "#ff6d00" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Impulse çıkış kuralı: yeşil→mavi/kırmızı flat long." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2, allowShort: true },
    tags: ["Elder", "Impulse", "PVT", "niche", "15m"],
  },
  {
    id: "niche_cmo_envelope",
    name: "Chande Momentum + Envelope",
    shortName: "CMO·Env",
    category: "niche",
    inspiredBy: "Tushar Chande CMO(14) + percent Envelope(20,2.5%) mean-reversion frame",
    summary: "CMO ±50 aşırı + Envelope bant — Chande momentum mean-rev kiti.",
    howTo: [
      "TF 15m–1h. Long: CMO <−50'den yukarı + fiyat alt Envelope'a değip rebound.",
      "Short: CMO >+50'den aşağı + üst Envelope rejection.",
      "Trend gününde (fiyat Envelope dışına kaçarsa) CMO sinyalini küçült.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "cmo", params: { period: 14 } },
      { type: "envelope", params: { period: 20, pct: 2.5 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.6, tip: "CMO uçlar nadir — sabır; R küçük tut." },
    backtestPreset: "rsiOsOb",
    backtestExtras: { rsiOs: 20, rsiOb: 80, useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 1.6 },
    tags: ["CMO", "Chande", "Envelope", "niche", "15m"],
  },
  {
    id: "niche_dpo_reg_channel",
    name: "DPO + Regression Channel",
    shortName: "DPO·Reg",
    category: "niche",
    inspiredBy: "Detrended Price Oscillator(21) cycle turns + Linear Regression Channel",
    summary: "DPO sıfır/cycle dönüşü + Reg Channel bant — trend'siz cycle ticareti.",
    howTo: [
      "TF 1h. Long: DPO↑0 ve fiyat Reg Channel alt/mid'den rebound.",
      "Short: DPO↓0 + üst kanal rejection.",
      "Güçlü trendde DPO gecikir — kanal eğimine bak.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "dpo", params: { period: 21 } },
      { type: "regChannel", params: { period: 20, mult: 2 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "DPO trend kaldırır — range/cycle piyasasında kullan." },
    backtestPreset: "zScorePullback",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 1.8, allowShort: true },
    tags: ["DPO", "Regression", "cycle", "niche", "1h"],
  },
  {
    id: "niche_mass_bb_pctb",
    name: "Mass Index + Bollinger %B",
    shortName: "Mass·%B",
    category: "niche",
    inspiredBy: "Donald Dorsey Mass Index(25) reversal bulge + Bollinger %B(20,2)",
    summary: "Mass Index 'reversal bulge' (27↑→26.5↓) + %B aşırı — volatilite dönüş kiti.",
    howTo: [
      "TF 1h–4h. Mass Index 27 üstünü görüp 26.5 altına inince dönüş setup'ı.",
      "Long teyit: %B <0.2'den yukarı. Short: %B >0.8'den aşağı.",
      "Bulge yokken %B sinyallerini tek başına kullanma.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "massIndex", params: { period: 25 } },
      { type: "bbPercentB", params: { period: 20, mult: 2 } },
      { type: "bollinger", params: { period: 20, mult: 2 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Mass Index seyrek sinyal verir — bekle, chase etme." },
    backtestPreset: "bbBreak",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.4, tpAtrMult: 2.2, allowShort: true },
    tags: ["MassIndex", "PercentB", "reversal", "niche", "1h"],
  },
  {
    id: "niche_chaikin_eom_mfi",
    name: "Chaikin Osc + EOM + MFI",
    shortName: "CHO·EOM",
    category: "niche",
    inspiredBy: "Chaikin Oscillator(3/10) + Ease of Movement(14) + Money Flow Index(14)",
    summary: "Üç hacim/akış aracı confluence — CHO kesişim + EOM>0 + MFI zone.",
    howTo: [
      "TF 15m–1h. Long: CHO↑0 + EOM>0 + MFI 20–50 (aşırı satımdan çıkış).",
      "Short: CHO↓0 + EOM<0 + MFI 50–80.",
      "Üçünden en az ikisi hizalanmadan girme.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "chaikinOsc", params: { fast: 3, slow: 10 } },
      { type: "eom", params: { period: 14 } },
      { type: "mfi", params: { period: 14 } },
      { type: "vwap", color: "#e040fb" },
    ],
    risk: { rMultiple: 2, tip: "Likit sembol şart; düşük hacimde EOM gürültülü." },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2, allowShort: true },
    scannerChips: ["vol2"],
    tags: ["Chaikin", "EOM", "MFI", "volume", "niche", "15m"],
  },
  {
    id: "niche_ppo_natr",
    name: "PPO + Normalized ATR",
    shortName: "PPO·NATR",
    category: "niche",
    inspiredBy: "Percentage Price Oscillator (12/26/9) + NATR(14) volatility filter",
    summary: "PPO sinyal/sıfır kesişimi + NATR ile volatilite rejimi filtresi.",
    howTo: [
      "TF 15m–1h. Long: PPO↑sinyal (tercihen 0 altından) ve NATR yükselen/orta.",
      "NATR çok düşükse (sıkışma) PPO kesişimini atla veya breakout bekle.",
      "NATR spike sonrası PPO dönüşü mean-rev olabilir — boyuta dikkat.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "ppo", params: { fast: 12, slow: 26, signal: 9 } },
      { type: "natr", params: { period: 14 } },
      { type: "ema", params: { period: 26 }, color: "#78909c" },
    ],
    risk: { rMultiple: 2, tip: "NATR rejimi değişmeden PPO'yu yalnız kullanma." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2.2, allowShort: true },
    tags: ["PPO", "NATR", "volatility", "niche", "15m"],
  },
  {
    id: "niche_coral_laguerre",
    name: "Coral Trend + Laguerre RSI",
    shortName: "Coral·Lag",
    category: "niche",
    inspiredBy: "ProReal Coral Trend(34) color flips + Laguerre RSI (gamma 0.5)",
    summary: "Coral renk/yön değişimi + Laguerre RSI OS/OB — PRT soft-trend kiti.",
    howTo: [
      "TF 15m. Long: Coral bull flip + Laguerre RSI <0.2'den yukarı.",
      "Short: Coral bear + Laguerre >0.8'den aşağı.",
      "Gamma 0.5 varsayılan; daha az lag için 0.7 dene (daha gürültülü).",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "coralTrend", params: { period: 34, mult: 0.4 }, color: "#26a69a" },
      { type: "laguerreRsi", params: { gamma: 0.5 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Coral whipsaw'da gecikmeli — Laguerre teyidi şart." },
    backtestPreset: "supertrendFlip",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.4, tpAtrMult: 2.2, allowShort: true },
    tags: ["Coral", "Laguerre", "ProReal", "niche", "15m"],
  },
  {
    id: "niche_nadaraya_ulcer",
    name: "Nadaraya-Watson + Ulcer Index",
    shortName: "NW·Ulcer",
    category: "niche",
    inspiredBy: "Nadaraya-Watson kernel bands + Ulcer Index(14) drawdown stress",
    summary: "NW bant mean-rev + Ulcer stres filtresi — kernel regression niş kiti.",
    howTo: [
      "TF 15m–1h. Long: fiyat NW alt banda değip mid'e dönüş + Ulcer düşüşe geçiyor.",
      "Short: üst banda rejection + Ulcer yükseliş (stres artışı short'a uygun).",
      "Bandwidth 8 varsayılan; daha düzgün bant için 12.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "nadarayaWatson", params: { bandwidth: 8, mult: 1.5 } },
      { type: "ulcerIndex", params: { period: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "NW repaint hissi verebilir — kapanış teyidi bekle." },
    backtestPreset: "zScorePullback",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 1.8, allowShort: true },
    tags: ["Nadaraya", "Ulcer", "kernel", "niche", "15m"],
  },
  {
    id: "niche_heikin_zigzag",
    name: "Heikin-Ashi Smooth + ZigZag + Fractals",
    shortName: "HA·ZZ",
    category: "niche",
    inspiredBy: "Smoothed Heikin-Ashi trend + ZigZag(5%) swings + Bill Williams Fractals",
    summary: "HA Smooth yön + ZigZag swing yapısı + fractal giriş — yapısal trend kiti.",
    howTo: [
      "TF 15m–1h. Long: HA Smooth bull + ZigZag higher-low + up fractal kırılımı.",
      "Short: HA bear + lower-high + down fractal.",
      "ZigZag %5 kripto için; hisse/BIST'te %3–4 dene.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "heikinAshiSmooth", params: { period: 10 } },
      { type: "zigzag", params: { pct: 5 } },
      { type: "fractals" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.2, tip: "ZigZag gecikmeli çizer — fractal + HA ile teyit et." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 10, slow: 21, useAtrStops: true, allowShort: true },
    tags: ["HeikinAshi", "ZigZag", "Fractals", "niche", "15m"],
  },
  {
    id: "niche_jurik_macd_ribbon",
    name: "Jurik MACD + JMA Ribbon",
    shortName: "JMACD·Rib",
    category: "niche",
    inspiredBy: "Jurik-smoothed MACD (12/26/9) + multi-length JMA Ribbon fan",
    summary: "Jurik MACD kesişim + Ribbon fan açılımı — klasik MACD'den daha temiz.",
    howTo: [
      "TF 15m. Long: Jurik MACD↑sinyal + Ribbon fan yukarı (kısa JMA'lar üstte).",
      "Short: MACD↓ + Ribbon aşağı fan.",
      "Ribbon dolanıkken (sıkışma) MACD kesişimini atla.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "jurikMacd", params: { fast: 12, slow: 26, signal: 9, phase: 50, power: 2 } },
      { type: "jmaRibbon", params: { phase: 50, power: 2 } },
      { type: "jurikVolty", params: { period: 20 } },
    ],
    risk: { rMultiple: 2, tip: "Ribbon açılımı + MACD birlikte; tek başına ribbon yetmez." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2.2, allowShort: true },
    tags: ["Jurik", "MACD", "Ribbon", "niche", "15m"],
  },
  {
    id: "niche_adaptive_macd_trail",
    name: "Adaptive MACD + Self-Aware Trail",
    shortName: "AdaMACD·SAT",
    category: "niche",
    inspiredBy: "ProReal Adaptive MACD + Self-Aware Trend Trail (QI-filtered ATR trail)",
    summary: "Volatiliteye uyumlu Adaptive MACD giriş + Self-Aware Trail çıkış.",
    howTo: [
      "TF 15m. Long: Adaptive MACD↑sinyal + fiyat Self-Aware Trail üstü.",
      "Trail kırılımı = çıkış. QI düşükken trail gevşer — boyutu küçült.",
      "Short simetrik.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "adaptiveMacd", params: { baseFast: 12, baseSlow: 26, signal: 9 } },
      { type: "selfAwareTrail", params: { atrLen: 10, mult: 3, qiLen: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.2, tip: "Trail kırılınca hemen flat — umut etme." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 2.5, allowShort: true },
    tags: ["AdaptiveMACD", "SelfAware", "ProReal", "niche", "15m"],
  },
  {
    id: "niche_rsi_bb_combo_dema",
    name: "RSI+BB Combo + DEMA",
    shortName: "RSIBB·DEMA",
    category: "niche",
    inspiredBy: "ProReal RSI+BB mean-reversion composite + DEMA(21) trend filter",
    summary: "Tek pane RSI×BB combo aşırı + DEMA yön — PRT mean-rev paketi.",
    howTo: [
      "TF 15m. Long: rsiBbCombo OS bölgesinden yukarı + fiyat DEMA üstü/yakın rebound.",
      "Short: OB'tan aşağı + DEMA altı.",
      "Güçlü trendde (fiyat DEMA'dan uzak) yalnız combo ile karşı trend alma.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "rsiBbCombo", params: { rsiLen: 14, bbLen: 20, bbMult: 2 } },
      { type: "dema", params: { period: 21 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.6, tip: "Mean-rev: sıkı stop, hızlı TP (1.5–2R)." },
    backtestPreset: "rsiOsOb",
    backtestExtras: { rsiOs: 30, rsiOb: 70, useAtrStops: true, slAtrMult: 1.1, tpAtrMult: 1.6 },
    tags: ["RSIBB", "DEMA", "ProReal", "meanrev", "niche", "15m"],
  },
  {
    id: "niche_ib_sweep_map",
    name: "Initial Balance + Sweep Reversal",
    shortName: "IB·Sweep",
    category: "niche",
    inspiredBy: "Market Profile Initial Balance + ProReal Sweep Reversal Map",
    summary: "Seans IB yüksek/düşük kırılımı veya fakeout + sweep reversal teyidi.",
    howTo: [
      "TF 5m–15m. IB oluştuktan sonra (ilk N bar) üst/alt kırılımı izle.",
      "Long: IB low sweep (likidite) + Sweep Reversal Map bull state + geri IB içi.",
      "Short: IB high sweep + bear reversal. SessionBars=4 kripto 15m için tipik.",
    ],
    timeframe: "5m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "initialBalance", params: { sessionBars: 4 } },
      { type: "sweepReversalMap", params: { lookback: 20, confirm: 2 } },
      { type: "vwap", color: "#e040fb" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "IB genişken breakout; dar iken sweep-fade tercih et." },
    backtestPreset: "emaRsiConfirm",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 2, allowShort: true },
    tags: ["InitialBalance", "Sweep", "session", "niche", "5m"],
  },
  {
    id: "niche_fib_gravity_pac",
    name: "Fib Gravity Clusters + PAC-lite",
    shortName: "Fib·PAC",
    category: "niche",
    inspiredBy: "ProReal Fibonacci Gravity Clusters + PAC-lite market structure",
    summary: "Fib cluster manyetik seviyeler + PAC HH/HL yapısı — seviye+yapı kiti.",
    howTo: [
      "TF 15m–1h. Long: fiyat discount Fib cluster'a gelip PAC HL/HH yapısı bozulmadan rebound.",
      "Short: premium cluster + LH/LL. Cluster dışı rastgele giriş yok.",
      "Stop: cluster karşı kenarı veya son swing.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "fibGravityClusters", params: { swing: 3, lookback: 80 } },
      { type: "pacLiteStructure", params: { swing: 2 } },
      { type: "ema", params: { period: 34 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.5, tip: "Cluster + yapı confluence şart; tek Fib seviyesine güvenme." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 9, slow: 34, useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 2.5, allowShort: true },
    tags: ["Fibonacci", "PAC", "structure", "niche", "15m"],
  },
  {
    id: "niche_double_jma_cci",
    name: "Double JMA + Jurik CCI",
    shortName: "DJMA·JCCI",
    category: "niche",
    inspiredBy: "Double-smoothed JMA trend + Jurik-filtered CCI(20) zero/±100 turns",
    summary: "DJMA yön filtresi + Jurik CCI aşırı/sıfır — çift Jurik momentum kiti.",
    howTo: [
      "TF 15m. Long: fiyat Double JMA üstü + Jurik CCI <−100'den yukarı veya↑0.",
      "Short: DJMA altı + CCI >+100'den aşağı.",
      "Phase 50 / power 2 standart Jurik ayarı.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "doubleJma", params: { period: 14, phase: 50, power: 2 }, color: "#26a69a" },
      { type: "jurikCci", params: { period: 20, jmaLen: 8, phase: 50, power: 2 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "DJMA lag'i az ama whipsaw olur — CCI teyidi bekle." },
    backtestPreset: "jurikOsBounce",
    backtestExtras: { useSignalExits: true, useAtrStops: true, slAtrMult: 1.3, allowShort: true },
    tags: ["Jurik", "DoubleJMA", "CCI", "niche", "15m"],
  },
  {
    id: "niche_var_reg_prt_dmi",
    name: "Var-Weighted Reg + PRT DMI",
    shortName: "VWR·DMI",
    category: "niche",
    inspiredBy: "Variance-Weighted Regression channel + ProReal DMI/ADX Pack",
    summary: "VWR kanal kırılımı/pullback + PRT ADX/DMI güç filtresi.",
    howTo: [
      "TF 1h. Long: close VWR mid/üst + PRT DI+ > DI− ve ADX>20.",
      "Short: mid altı + DI− > DI+ . ADX<18'de kanal mean-rev (kırılım değil).",
      "Period 30 VWR swing için; scalpte 20.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "varWeightedReg", params: { period: 30, mult: 2 } },
      { type: "prtDmiPack", params: { period: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.2, tip: "ADX zayıfken breakout alma; mean-rev'e geç." },
    backtestPreset: "diAdxTrend",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 2.5, allowShort: true },
    tags: ["VarWeighted", "DMI", "ADX", "ProReal", "niche", "1h"],
  },

  // ——— Yeni niş göstergeler (SMI, Coppock, HalfTrend…) ———
  {
    id: "niche_smi_vidya",
    name: "SMI + VIDYA Trend Filtre",
    shortName: "SMI·VIDYA",
    category: "niche",
    inspiredBy: "Stochastic Momentum Index (14/20/5) + Chande VIDYA trend filter",
    summary:
      "SMI sinyal kesişimi + VIDYA yön filtresi — momentum + uyarlanabilir MA niş kiti.",
    howTo: [
      "TF 15m. Long: SMI↑sinyal (tercihen 0 altından) + fiyat VIDYA üstü.",
      "Short: SMI↓sinyal + fiyat VIDYA altı. SMI ±40 uçlarda mean-rev dikkat.",
      "VIDYA(14) crypto/USDT için; günlükte period 20 deneyebilirsin.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "smi", params: { qLength: 14, rLength: 20, signal: 5 } },
      { type: "vidya", params: { period: 14 }, color: "#26a69a" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "İki onay yoksa işlem yok; chop'ta SMI flip artar." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2, allowShort: true },
    tags: ["SMI", "VIDYA", "niche", "15m"],
  },
  {
    id: "niche_coppock_frama",
    name: "Coppock + FRAMA",
    shortName: "Copp·FRAMA",
    category: "niche",
    inspiredBy: "Coppock Curve (ROC14+11, WMA10) + Ehlers FRAMA adaptive MA",
    summary: "Coppock sıfır/dönüş sinyali + FRAMA trend — uzun soluklu momentum kiti.",
    howTo: [
      "TF 1h–4h (Coppock gecikmeli). Long: Coppock↑0 veya dip dönüşü + fiyat FRAMA üstü.",
      "Short: Coppock↓0 + FRAMA altı. Scalpte ROC 11+14 aynı kalır, sabır şart.",
      "FRAMA(16) kırılımı trend teyidi; whipsaw'da bekle.",
    ],
    timeframe: "1h",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "coppock", params: { rocLong: 14, rocShort: 11, wmaPeriod: 10 } },
      { type: "frama", params: { period: 16 }, color: "#ab47bc" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2.5, tip: "Coppock lag'li — erken kovalama; FRAMA teyidi bekle." },
    backtestPreset: "emaCross",
    backtestExtras: { fast: 16, slow: 34, useAtrStops: true, slAtrMult: 1.5, tpAtrMult: 2.5, allowShort: true },
    tags: ["Coppock", "FRAMA", "niche", "1h"],
  },
  {
    id: "niche_squeeze_halftrend",
    name: "Squeeze Momentum + HalfTrend",
    shortName: "Sqz·HT",
    category: "niche",
    inspiredBy: "TTM/LazyBear Squeeze Momentum + HalfTrend ATR channel",
    summary: "BB-KC sıkışma sonrası mom hist + HalfTrend yön — squeeze breakout kiti.",
    howTo: [
      "TF 15m. Squeeze On (sqz=1) bitince mom hist yönünde gir; HalfTrend aynı yön olmalı.",
      "Long: squeeze release + mom>0 + fiyat HalfTrend üstü.",
      "Short: mom<0 + HT bear. Stop: HT karşı kanal / ATR.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "squeezeMomentum", params: { length: 20, bbMult: 2, kcMult: 1.5 } },
      { type: "halfTrend", params: { amplitude: 2, channelDeviation: 2, atrPeriod: 100 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Squeeze yokken mom sinyali zayıf — sabır." },
    backtestPreset: "bbBreak",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 2, allowShort: true },
    tags: ["Squeeze", "HalfTrend", "niche", "15m"],
  },
  {
    id: "niche_waddah_ssl",
    name: "Waddah Attar + SSL Channel",
    shortName: "WAE·SSL",
    category: "niche",
    inspiredBy: "Waddah Attar Explosion vs BB width + SSL Hybrid channel",
    summary: "WAE patlama (trend>explosion) + SSL kanal flip — volatilite breakout kiti.",
    howTo: [
      "TF 15m. Long: WAE Up > Explosion (ve Dead Zone üstü) + SSL Up > SSL Down (bull flip).",
      "Short: WAE Down > Explosion + SSL bear. Explosion altında işlem yok.",
      "Sensitivity 150 klasik; crypto'da 100–200 dene.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "waddahAttar", params: { fast: 20, slow: 40, bbPeriod: 20, bbMult: 2, sensitivity: 150 } },
      { type: "sslChannel", params: { period: 10 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "Dead Zone altındaki 'patlama' sahte — filtrele." },
    backtestPreset: "macdCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2.2, allowShort: true },
    tags: ["Waddah", "SSL", "niche", "15m"],
  },
  {
    id: "niche_vfi_rangefilter",
    name: "VFI + Range Filter",
    shortName: "VFI·RF",
    category: "niche",
    inspiredBy: "Volume Flow Indicator (LazyBear) + Ehlers/TV Range Filter",
    summary: "VFI para akışı + Range Filter yön — hacim + sticky filter niş kiti.",
    howTo: [
      "TF 15m–1h. Long: VFI↑sinyal (veya VFI>0) + fiyat Range Filter üstü / dir↑.",
      "Short: VFI↓0 + RF altı. Period 130 VFI günlük/1h için; 15m'de 50–80 dene.",
      "RF mult 2.5 standart; scalpte 2.0.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "vfi", params: { period: 80, coef: 0.2, vcoef: 2.5, signal: 5 } },
      { type: "rangeFilter", params: { period: 20, mult: 2.5 }, color: "#00bcd4" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "VFI hacimsiz pair'de zayıf — likit USDT çiftleri tercih et." },
    backtestPreset: "emaCross",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.4, tpAtrMult: 2.2, allowShort: true },
    tags: ["VFI", "RangeFilter", "volume", "niche", "15m"],
  },
  {
    id: "niche_chop_elder_bop",
    name: "Choppiness + Elder Ray + BOP",
    shortName: "CHOP·Elder·BOP",
    category: "niche",
    inspiredBy: "Choppiness Index regime + Elder Ray bull/bear + Balance of Power",
    summary: "CHOP rejim filtresi + Elder Ray güç + BOP — trend/range ayırıcı niş kit.",
    howTo: [
      "TF 15m–1h. CHOP <38.2 → trend modu: Elder Bull>0 + BOP>0 long.",
      "CHOP >61.8 → range: uçlardan mean-rev (Elder Bear çok negatif rebound).",
      "BOP(14) teyit; çelişkide işlem yok.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "choppiness", params: { period: 14 } },
      { type: "elderRay", params: { period: 13 } },
      { type: "bop", params: { smooth: 14 } },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 1.8, tip: "Önce CHOP rejimini seç; sonra Elder/BOP." },
    backtestPreset: "rsiOsOb",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.2, tpAtrMult: 1.8, allowShort: true },
    tags: ["Choppiness", "ElderRay", "BOP", "niche", "15m"],
  },
  {
    id: "niche_softtrend_adx",
    name: "SoftTrend + ADX",
    shortName: "Soft·ADX",
    category: "niche",
    inspiredBy: "SoftTrend ATR filter + classic ADX/DMI strength",
    summary: "SoftTrend yön çizgisi + ADX güç filtresi — yumuşak trend takip kiti.",
    howTo: [
      "TF 15m. Long: fiyat SoftTrend line üstü + ADX>20 ve DI+ > DI−.",
      "Short: line altı + DI− > DI+. ADX<18'de SoftTrend flip'lerini atla.",
      "Mult 1.5 soft; daha az flip için 2.0.",
    ],
    timeframe: "15m",
    allowShort: true,
    replaceIndicators: true,
    indicators: [
      { type: "softTrend", params: { period: 20, atrPeriod: 14, mult: 1.5 }, color: "#e040fb" },
      { type: "adx", params: { period: 14 } },
      { type: "ema", params: { period: 50 }, color: "#78909c" },
      { type: "atr", params: { period: 14 } },
    ],
    risk: { rMultiple: 2, tip: "ADX filtresi olmadan SoftTrend chop'ta sık flip." },
    backtestPreset: "diAdxTrend",
    backtestExtras: { useAtrStops: true, slAtrMult: 1.3, tpAtrMult: 2.2, allowShort: true },
    tags: ["SoftTrend", "ADX", "niche", "15m"],
  },
];

export function strategyById(id: string): StrategyPack | undefined {
  return STRATEGY_PACKS.find((s) => s.id === id);
}

/** Killzone windows in Europe/Istanbul (UTC+3) — illustrative ICT-style. */
export const KILLZONES_TR = [
  { id: "asia", label: "Asya range", start: "02:00", end: "05:00" },
  { id: "london", label: "Londra KZ", start: "10:00", end: "13:00" },
  { id: "ny_am", label: "NY AM KZ", start: "15:30", end: "18:00" },
  { id: "ny_pm", label: "NY PM / Silver", start: "22:00", end: "23:00" },
] as const;
